version: '3.3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
      - --spi-required-action-age-confirmation-minimum-age=10
    volumes:
      - ./build/libs:/opt/keycloak/providers
      - ./themes:/opt/keycloak/themes